version: '3'

services:
  mqtt-test-sec:
    #image: conixcenter/arena-broker-test 
    image: conixcenter/arena-broker
    volumes:
      - ./mosquitto-sec.conf:/mosquitto/config/mosquitto.conf:ro # mount local config file to /mosquitto/config/mosquitto.conf in the container
      - ../arena-services-docker/data/keys/jwt.public.der:/pubsubkey.der:ro # pubsub key available to service
      - ../arena-services-docker/data/certbot/conf:/etc/letsencrypt:ro # mount certs volume (see conf/mosquitto.conf to see how the files are used)
    ports:
      - 11883:1883/tcp # mqtt; map port for listener configured in /conf/mosquitto.conf
      - 19001:9001/tcp # mqtt-ws
      - 18083:8083/tcp # mqtt-wss
      - 18883:8883/tcp # mqtt-tls

#  mqtt-test-br1:
#    image: conixcenter/arena-broker 
#    volumes:
#      - ./mosquitto-br.conf:/mosquitto/config/mosquitto.conf:ro
#      - ../arena-services-docker/data/keys/jwt.public.der:/pubsubkey.der:ro 
#      - ../arena-services-docker/data/certbot/conf:/etc/letsencrypt:ro
#    ports:
#      - 28883:8883/tcp # mqtt-tls
#    depends_on:
#      - mqtt-test-sec

#   mqtt-test-br2:
#     image: conixcenter/arena-broker 
#     volumes:
#       - ./mosquitto-br.conf:/mosquitto/config/mosquitto.conf:ro
#       - ../arena-services-docker/data/keys/jwt.public.der:/pubsubkey.der:ro 
#       - ../arena-services-docker/data/certbot/conf:/etc/letsencrypt:ro
#     ports:
#       - 28884:8883/tcp # mqtt-tls
#     depends_on:
#       - mqtt-test-sec

#   mqtt-test-br3:
#     image: conixcenter/arena-broker 
#     volumes:
#       - ./mosquitto-br.conf:/mosquitto/config/mosquitto.conf:ro
#       - ../arena-services-docker/data/keys/jwt.public.der:/pubsubkey.der:ro 
#       - ../arena-services-docker/data/certbot/conf:/etc/letsencrypt:ro
#     ports:
#       - 28885:8883/tcp # mqtt-tls
#     depends_on:
#       - mqtt-test-sec


        #  mosquitto-exporter:
        #    image: sapcc/mosquitto-exporter
        #    environment:
        #        - BROKER_ENDPOINT=tcp://mqtt-test-sec:1883
        #        - MQTT_USER=cli
        #        - MQTT_PASS=<token>
        #    ports:
        #        - 9234:9234
        #    depends_on:
        #        - mqtt-test-sec
