version: '3'

services:
  mqtt-test-sec:
    image: conixcenter/arena-broker-test 
    volumes:
      - ./mosquitto-sec.conf:/mosquitto/config/mosquitto.conf:ro # mount local config file to /mosquitto/config/mosquitto.conf in the container
      - ../arena-services-docker/data/keys/jwt.public.der:/pubsubkey.der:ro # pubsub key available to service
      - ../arena-services-docker/data/certbot/conf:/etc/letsencrypt:ro # mount certs volume (see conf/mosquitto.conf to see how the files are used)
    ports:
      - 11883:1883/tcp # mqtt; map port for listener configured in /conf/mosquitto.conf
      - 19001:9001/tcp # mqtt-ws
      - 18083:8083/tcp # mqtt-wss
      - 18883:8883/tcp # mqtt-tls

  mqtt-test-nosec:
    image: conixcenter/arena-broker-test 
    volumes:
        - ./mosquitto-nosec.conf:/mosquitto/config/mosquitto.conf:ro # mount local config file to /mosquitto/config/mosquitto.conf in the container
    ports:
      - 21883:1883/tcp # mqtt; map port for listener configured in /conf/mosquitto.conf

 

